name: wagazap.api

services:
  api:
    image: nandoburgos/wagazap.api
    container_name: wagazap.api
    environment:
      - PORT=4105
      - DATABASE_URL=mysql://burgos:ewhblt69@mysql:3306/wagazap
    ports:
      - "4105:4105"
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    # deploy:
      # resources:
        # limits:
          # cpus: '2'
          # memory: 2048M

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=wagazap
      - MYSQL_USER=burgos
      - MYSQL_PASSWORD=ewhblt69
      - MYSQL_ROOT_PASSWORD=ewhblt69
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"
    restart: unless-stopped

volumes:
  static_volume:
    name: "wagazap_static_files"
  mysql-data:
    name: "wagazap_mysql_data"

networks:
  default:
    name: wagazap_network