name: wagazap_api

services:
  api:
    image: nandoburgos/wagazap.api
    container_name: wagazap.api
    environment:
      - PORT=8105
      - DATABASE_URL=mysql://burgos:ewhblt69@mysql:3306/wagazap
      - URL=https://apichat.nandoburgos.dev
    ports:
      - "8105:8105"
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.5'
    #       memory: 1512M

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=wagazap
      - MYSQL_USER=burgos
      - MYSQL_PASSWORD=ewhblt69
      - MYSQL_ROOT_PASSWORD=ewhblt69
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "4306:3306"
    restart: unless-stopped

volumes:
  static_volume:
    name: "wagazap_static_files"
  mysql-data:
    name: "wagazap_mysql_data"

networks:
  default:
    name: wagazap_network